version: 2
updates:
  - package-ecosystem: pip
    directory: "/"
    labels:
      - "pr: dependency-update"
    schedule:
      interval: monthly
      time: "06:00"
    open-pull-requests-limit: 3
  - package-ecosystem: "github-actions"
    directory: "/"
    labels:
      - "pr: dependency-update"
    schedule:
      interval: monthly
      time: "06:00"
    open-pull-requests-limit: 3
