comment: false
codecov:
  branch: main

coverage:
  precision: 2
  round: down
  range: "60...100"

  status:
    patch: off
    project:
      default:
        target: 50%

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

ignore:
  - "tests"
