[tools]
pre-commit = "4.2"
python = "3.13"
uv = "0.8.3"

[settings]
experimental = true
auto_install = false

[env]
_.python.venv = { path = ".venv" }

[task_config]
includes = ["tasks"]

[tasks."hassio:start"]
description = "Start Hassio"
run = "docker compose -f docker-compose.yml up --remove-orphans"

[tasks."hassio:stop"]
description = "Stop Hassio"
run = "docker compose -f docker-compose.yml down"
