  version: 3

  tasks:
    tests:
      cmds:
        - python -m  pytest tests -rxf -x -v -l --cov=./ --cov-report=xml

    coverage:
      deps:
        - test
      cmds:
        - python3 -m coverage report --skip-covered

    develop:
      cmds:
        - hass -c . --debug

    install:
      cmds:
        - poetry install

    setup:
      cmds:
        - poetry shell
        - task: install
        - pre-commit install --install-hooks
        - pre-commit install --hook-type commit-msg --hook-type pre-push
