name: Test

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

concurrency:
  group: test-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run:
    name: With pytest
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout the repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - uses: jdx/mise-action@v4
        name: 🤖 Mise action
        with:
          version: 2026.3.15

      - name: 📦 Install requirements
        run: mise project:setup

      - name: 🏃 Run tests
        run: mise project:tests

      - name: 📊 Generate coverage
        run: mise project:coverage

      - name: 📤 Upload coverage to Codecov
        uses: codecov/codecov-action@v6
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          name: pytest
          fail_ci_if_error: true
          files: coverage.xml
